Controllers/PrestamoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lib360;

namespace Lib360.Controllers
{
    public class PrestamoController : Controller
    {
        private LIB360Entities db = new LIB360Entities();

        // GET: Prestamo
        public ActionResult Index()
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            var prestamo = db.Prestamo.Include(p => p.Libro).Include(p => p.Usuario).OrderByDescending(p=>p.FechaInicio);
            Session["IDPrestamo"] =null;
            return View(prestamo.ToList());
        }

        // GET: Prestamo/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamo prestamo = db.Prestamo.Find(id);
            if (prestamo == null)
            {
                return HttpNotFound();
            }
            return View(prestamo);
        }

        // GET: Prestamo/Create
        public ActionResult Create()
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            ViewBag.IDLibro = new SelectList(db.Libro, "IDLibro", "Nombre");
            ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre");
            return PartialView();
        }

        // POST: Prestamo/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDLibro,IDUsuario,FechaInicio,FechaFin,Regresado,IDPrestamo")] Prestamo prestamo)
        {
            //14 dias
            DateTime dt = (DateTime)prestamo.FechaInicio;
            System.TimeSpan duration = new System.TimeSpan(14, 0, 0, 0);
            prestamo.FechaFin = dt.Add(duration);
            prestamo.Regresado = 0;
            if (ModelState.IsValid)
            {
                db.Prestamo.Add(prestamo);
                var libro = db.Libro.FirstOrDefault(x => x.IDLibro == prestamo.IDLibro);
                if (libro.Cantidad == 0 || prestamo.FechaInicio < DateTime.Now)
                {
                    return PartialView(prestamo);
                }
                libro.Cantidad = libro.Cantidad-1;
                db.Entry(libro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDLibro = new SelectList(db.Libro, "IDLibro", "Nombre", prestamo.IDLibro);
            ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", prestamo.IDUsuario);
            return PartialView(prestamo);
        }

        // GET: Prestamo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamo prestamo = db.Prestamo.Find(id);
            if (prestamo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDLibro = new SelectList(db.Libro, "IDLibro", "Nombre", prestamo.IDLibro);
            ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", prestamo.IDUsuario);
            Session["IDPrestamo"] = Convert.ToInt32(id);
            return PartialView(prestamo);
        }

        // POST: Prestamo/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDLibro,IDUsuario,FechaInicio,FechaFin,Regresado,IDPrestamo")] Prestamo prestamo)
        {
            int id = (int)Convert.ToInt64(Session["IDPrestamo"]);
            var pres = db.Prestamo.Find(id);
            prestamo = pres;
            prestamo.Regresado = 1;
            if (ModelState.IsValid)
            {
                db.Entry(prestamo).State = EntityState.Modified;
                var libro = db.Libro.FirstOrDefault(x => x.IDLibro == prestamo.IDLibro);
                libro.Cantidad = libro.Cantidad + 1;
                db.Entry(libro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IDLibro = new SelectList(db.Libro, "IDLibro", "Nombre", prestamo.IDLibro);
            ViewBag.IDUsuario = new SelectList(db.Usuario, "IDUsuario", "Nombre", prestamo.IDUsuario);
            return PartialView(prestamo);
        }

        // GET: Prestamo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prestamo prestamo = db.Prestamo.Find(id);
            if (prestamo == null)
            {
                return HttpNotFound();
            }
            return PartialView(prestamo);
        }

        // POST: Prestamo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prestamo prestamo = db.Prestamo.Find(id);
            db.Prestamo.Remove(prestamo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult PrestamoUsuario()
        {
            if (Session["UserEmail"] == null && Session["UserName"] == null && Session["UserID"] == null && Session["UserRol"] == null)
            {
                return RedirectToAction("SignIn", "Usuario");
            }
            int id = (int)Convert.ToInt64(Session["UserID"]);
            //var prestamo = db.Prestamo.Include(p => p.Libro).Include(p => p.Usuario).OrderByDescending(p => p.FechaInicio);
            var prestamo = db.Prestamo.Where(p => p.IDUsuario == id).Include(p => p.Libro).Include(p => p.Usuario).OrderByDescending(p => p.FechaInicio);
            Session["IDPrestamo"] = null;
            return View(prestamo.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Prestamo/Create.cshtml
@model Lib360.Prestamo

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()
	<form>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="modal-header">
			<h4 class="modal-title">Crear Préstamo</h4>

			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		</div>
		<div class="modal-body">
			<div class="form-group">
				<label for="Usuario">Usuario</label>
				@Html.DropDownList("IDUsuario", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IDLibro, "", new { @class = "text-danger" })
			</div>
			<div class="form-group">
				<label for="Libro">Libro</label>
				@Html.DropDownList("IDLibro", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.IDLibro, "", new { @class = "text-danger" })
			</div>
			<div class="form-group">
				<label for="FechaInicio">Fecha de Inicio</label>
				@Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
				@Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
			</div>
		</div>
		<div class="modal-footer">
			<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
			<input type="submit" class="btn btn-success" value="Crear">
		</div>
	</form>
}

Views/Prestamo/Delete.cshtml
@model Lib360.Prestamo



<div class="modal-header">
	<h4 class="modal-title">Eliminar préstamo</h4>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>
<div class="modal-body">
	<p>¿Está seguro de eliminar este préstamo?</p>
	<p class="text-warning"><small>Esta acción no se puede deshacer.</small></p>
</div>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="modal-footer">
		<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
		<input type="submit" class="btn btn-danger" value="Borrar">
	</div>
}

Views/Prestamo/Edit.cshtml
@model Lib360.Prestamo
<div class="modal-header">
	<h4 class="modal-title">Marcar como regresado</h4>
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
</div>
<div class="modal-body">
	<p>¿Está seguro de marcar como regresado?</p>
	<p class="text-warning"><small>Esta acción no se puede deshacer.</small></p>
</div>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="modal-footer">
		<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancelar">
		<input type="submit" class="btn btn-primary" value="Marcar como regresado">
	</div>
}

Views/Prestamo/Index.cshtml
@model IEnumerable<Lib360.Prestamo>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
</head>
<div class="wrapper">
	<div id="content-page" class="content-page " style="padding-left:0px">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="iq-card">
						<div class="iq-card-header d-flex justify-content-between">
							<div class="iq-header-title">
								<h4 class="card-title">Préstamos</h4>
							</div>
						</div>
						<div class="iq-card-body">
							<div class="table-responsive">
								<div class="row justify-content-between">
									<div class="col-sm-12 col-md-6">
										<div id="user_list_datatable_info" class="dataTables_filter">
											<form class="mr-3 position-relative">
												<div class="form-group mb-0">
													<input type="search" class="form-control" id="exampleInputSearch" placeholder="Buscar" aria-controls="user-list-table">
												</div>
											</form>
										</div>

									</div>
									<div class="col-sm-12 col-md-6">
										<div class="user-list-files d-flex float-right">

											<a class="Create iq-bg-primary" href="javascript:void(0);" data-placement="top" title="" data-original-title="Crear" data-toggle="modal">Crear nuevo préstamo</a>
										</div>
									</div>

								</div>
								<table id="user-list-table" class="table table-striped table-bordered mt-4" role="grid" aria-describedby="user-list-page-info">
									<thead>
										<tr>
											<th>Usuario</th>
											<th>Libro</th>
											<th>Fecha Inicio</th>
											<th>Fecha Fin</th>
											<th>Regresado</th>
											<th>Acciones</th>
										</tr>
										@foreach (var item in Model)
										{
											<tr>
												<td>
													@Html.DisplayFor(modelItem => item.Usuario.Nombre) @Html.DisplayFor(modelItem => item.Usuario.Apellido)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.Libro.Nombre)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.FechaInicio)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.FechaFin)
												</td>
												<td>@if (item.Regresado == 0)
														{
															<a style="color:red">No regresado</a>
														}
												@if (item.Regresado == 1)
														{
															<a style="color: darkseagreen">Regresado</a>
														}
													
												</td>
												<td>
													<div class="d-flex align-items-center list-user-action">
														@if (item.Regresado == 0)
														{
															<a href="javascript:void(0);" class="Edit iq-bg-primary edit" data-id="@item.IDPrestamo" data-placement="top" title="" data-original-title="Marcar como regresado" data-toggle="modal"><i class="ri-checkbox-line"></i></a>
															<a href="javascript:void(0);" class="Delete iq-bg-primary delete" data-id="@item.IDPrestamo" data-placement="top" title="" data-original-title="Eliminar" data-toggle="modal"><i class="ri-delete-bin-line"></i></a>

														}
													</div>
												</td>
											</tr>
										}

								</table>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div id='myModal' class='modal fade' tabindex="-1" role="dialog">
	<div class="modal-dialog ">
		<div class="modal-content">

			<div id='myModalContent'></div>
		</div>
	</div>
</div>

<div id='myModal2' class='modal fade' tabindex="-1" role="dialog">
	<div class="modal-dialog ">
		<div class="modal-content">

			<div id='myModalContent2'></div>
		</div>
	</div>
</div>

<div id='myModal3' class='modal fade' tabindex="-1" role="dialog">
	<div class="modal-dialog ">
		<div class="modal-content">

			<div id='myModalContent3'></div>
		</div>
	</div>
</div>
@section scripts{
	<script src="~/Content/js/jquery-3.3.1.min.js"></script>
	<script>
		const PartialView1 = '@Url.Action("Create","Prestamo")'
		/*var PartialView1 = '/Libro/Create';*/
		$(function () {
			$(".Create").click(function () {
				debugger;
				var id = '2';
				var options = { "backdrop": true, keyboard: true };
				$.ajax({
					type: "GET",
					url: PartialView1,
					contentType: "application/json; charset=utf-8",
					data: { "Id": id },
					datatype: "json",
					success: function (data) {
						debugger;
						$('#myModalContent').html(data);
						$('#myModal').modal(options);
						$('#myModal').modal('show');

					},
					error: function () {
						alert("Dynamic content load failed.");
					}
				});
			});
			//$("#closebtn").on('click',function(){
			//    $('#myModal').modal('hide');

			$("#closbtn").click(function () {
				$('#myModal').modal('hide');
			});
		});
	</script>
	<script>
		const PartialView2 = '@Url.Action("Edit","Prestamo")'
		$(function () {
			$(".Edit").click(function () {
				debugger;
				var $buttonClicked = $(this);
				var id = $buttonClicked.attr('data-id');
				var options = { "backdrop": true, keyboard: true };
				$.ajax({
					type: "GET",
					url: PartialView2,
					contentType: "application/json; charset=utf-8",
					data: { "Id": id },
					datatype: "json",
					success: function (data) {
						debugger;
						$('#myModalContent2').html(data);
						$('#myModal2').modal(options);
						$('#myModal2').modal('show');

					},
					error: function () {
						alert("Dynamic content load failed.");
					}
				});
			});
			//$("#closebtn").on('click',function(){
			//    $('#myModal').modal('hide');

			$("#closbtn").click(function () {
				$('#myModal2').modal('hide');
			});
		});
	</script>

	<script>
		const PartialView3 = '@Url.Action("Delete", "Prestamo")'
		$(function () {
			$(".Delete").click(function () {
				debugger;
				var $buttonClicked = $(this);
				var id = $buttonClicked.attr('data-id');
				var options = { "backdrop": true, keyboard: true };
				$.ajax({
					type: "GET",
					url: PartialView3,
					contentType: "application/json; charset=utf-8",
					data: { "Id": id },
					datatype: "json",
					success: function (data) {
						debugger;
						$('#myModalContent3').html(data);
						$('#myModal3').modal(options);
						$('#myModal3').modal('show');

					},
					error: function () {
						alert("Dynamic content load failed.");
					}
				});
			});
			//$("#closebtn").on('click',function(){
			//    $('#myModal').modal('hide');

			$("#closbtn").click(function () {
				$('#myModal3').modal('hide');
			});
		});
	</script>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")

}

Views/Prestamo/PrestamoUsuario.cshtml
@model IEnumerable<Lib360.Prestamo>

@{
	ViewBag.Title = "Préstamos";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/line-awesome/1.3.0/line-awesome/css/line-awesome.min.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
</head>
<div class="wrapper">
	<div id="content-page" class="content-page " style="padding-left:0px">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="iq-card">
						<div class="iq-card-header d-flex justify-content-between">
							<div class="iq-header-title">
								<h4 class="card-title">Préstamos</h4>
							</div>
						</div>
						<div class="iq-card-body">
							<div class="table-responsive">
								<table id="user-list-table" class="table table-striped table-bordered mt-4" role="grid" aria-describedby="user-list-page-info">
									<thead>
										<tr>
											<th>Usuario</th>
											<th>Libro</th>
											<th>Fecha Inicio</th>
											<th>Fecha Fin</th>
											<th>Regresado</th>
										</tr>
										@foreach (var item in Model)
										{
											<tr>
												<td>
													@Html.DisplayFor(modelItem => item.Usuario.Nombre) @Html.DisplayFor(modelItem => item.Usuario.Apellido)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.Libro.Nombre)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.FechaInicio)
												</td>
												<td>
													@Html.DisplayFor(modelItem => item.FechaFin)
												</td>
												<td>
													@if (item.Regresado == 0)
													{
														<a style="color:red">No regresado</a>
													}
												@if (item.Regresado == 1)
												{
													<a style="color: darkseagreen">Regresado</a>
												}

											</td>
											
										</tr>
									}

								</table>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>